export const navLinks = {
  interior: "/services/interior",
  exterior: "/services/exterior",
  maintenance: "/services/maintenance",
  kandinsky: "https://k-floors.com",
  woodAndTimber: "/wood-and-timber",
  calvaryComposite: "/calvary-composite",
  accoya: "/accoya",
  dasso: "/dasso-ctech",
  osmo: "/osmo",
  sandAndVanish: "/sand-and-vanish",
  aboutUs: "/about-us",
  blog: "/blog",
  projects: "/projects",
  contactUs: "/contact-us",
};
