const definitionsAndKeyTerms: string[] = [
  "Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
  "Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Calvary Carpentry, (54 Senoko Rd, Singapore 758118), that is responsible for your information under this Privacy Policy",
  "Country: where Calvary Carpentry or the owners/founders of Calvary Carpentry are based, in this case is Singapore",
  "Customer: refers to the company, organization or person that signs up to use the Calvary Carpentry Service to manage the relationships with your consumers or service users.",
  "Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Calvary Carpentry and use the services.",
  "IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.",
  "Personnel: refers to those individuals who are employed by Calvary Carpentry or are under contract to perform a service on behalf of one of the parties.",
  "Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.",
  "Service: refers to the service provided by Calvary Carpentry as described in the relative terms (if available) and on this platform.",
  "Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
  "Website: Calvary Carpentry’s site, which can be accessed via this URL: https://calvarycarpentry.com",
  "You: a person or entity that is registered with Calvary Carpentry to use the Services.",
];

const DefinitionsKeyTerms = () => {
  return (
    <div className="container-cp">
      <div className="space-y-2">
        <h2 className="font-semibold text-center">Definitions and key terms</h2>
        <p>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
      </div>
      <ul className="flex flex-col gap-y-3 mt-4 list-inside list-disc">
        {definitionsAndKeyTerms.map((term, termIdx) => (
          <li key={`term-${termIdx}`} className="text-sm">
            {term}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default DefinitionsKeyTerms;
